cookie:
  expiry_days: 30
  key: some_signature_key
  name: some_cookie_name
credentials:
  usernames:
    admin:
      email: jhlee@jyoungsoft.com
      name: admin
      password: $2b$12$f.St1zklstkZ23XYMDWClek6iJz.mxxCzcI7BhUYOC4SQPAXfSuDW
    eotkdch:
      email: eotkdch1993@naver.com
      name: eotkdch
      password: $2b$12$smjHhu9EukZm6lDulFPs9OEzReg8LnrJh5L5CLkeIC6pF3EWMQyme
    ghwnsgkgk:
      email: ghwnsgkgk@kakao.com
      name: leejoonho
      password: $2b$12$2axUlVG0XE4hx3i0GaM7weU3Z5FjADjsZasSOOsKekxIZwtcBLRca
    wnsghwnsgh:
      email: ghwnsgkgk@nate.com
      name: wnsgh774
      password: $2b$12$J11KxFJbz90Zvj.VSXJv1ePhTikZA3PGr3hFFxJOpQdS10GCwCDyW
preauthorized:
  emails:
  - ghwnsgkgkgk@gmail.com
