cookie:
  expiry_days: 30
  key: some_signature_key
  name: some_cookie_name
credentials:
  usernames:
    admin:
      email: jhlee@jyoungsoft.com
      name: admin
      password: $2b$12$f.St1zklstkZ23XYMDWClek6iJz.mxxCzcI7BhUYOC4SQPAXfSuDW
    ghwnsgkgk:
      email: ghwnsgkgk@kakao.com
      name: "\uC774\uC900\uD638"
      password: $2b$12$2axUlVG0XE4hx3i0GaM7weU3Z5FjADjsZasSOOsKekxIZwtcBLRca
    wnsgh:
      email: ghwnsgkgk@nate.com
      name: Lee joonho
      password: $2b$12$3bp1ndxaMr5i0HtrKM9Oe.PB/dEaO54Z0nI.P8UzcKH9q2Am6Lt2.
    wnsgh222:
      email: ghwnsglgl@nate.com
      name: "\uC774\uC900\uD638"
      password: $2b$12$iymrpbXv1Aw3WzSIVQPCi.RrfXhWt2p7n2vo/h/8474r3FooJ6By6
preauthorized:
  emails:
  - ghwnsgkgkgk@gmail.com
